//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoaForm.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServisimSoap")]
    public interface ServisimSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: Generating message contract since message GetProductRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoaForm.ServiceReference1.GetProductResponse GetProduct(SoaForm.ServiceReference1.GetProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<SoaForm.ServiceReference1.GetProductResponse> GetProductAsync(SoaForm.ServiceReference1.GetProductRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class urunler : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int kategoriIDField;
        
        private string adiField;
        
        private string kisaaciklamaField;
        
        private string aciklamaField;
        
        private string resimField;
        
        private string anasayfaaciklamaField;
        
        private System.Nullable<bool> anasayfadagosterField;
        
        private string googleanahtarField;
        
        private string googleaciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int kategoriID {
            get {
                return this.kategoriIDField;
            }
            set {
                this.kategoriIDField = value;
                this.RaisePropertyChanged("kategoriID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string adi {
            get {
                return this.adiField;
            }
            set {
                this.adiField = value;
                this.RaisePropertyChanged("adi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string kisaaciklama {
            get {
                return this.kisaaciklamaField;
            }
            set {
                this.kisaaciklamaField = value;
                this.RaisePropertyChanged("kisaaciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
                this.RaisePropertyChanged("aciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string resim {
            get {
                return this.resimField;
            }
            set {
                this.resimField = value;
                this.RaisePropertyChanged("resim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string anasayfaaciklama {
            get {
                return this.anasayfaaciklamaField;
            }
            set {
                this.anasayfaaciklamaField = value;
                this.RaisePropertyChanged("anasayfaaciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> anasayfadagoster {
            get {
                return this.anasayfadagosterField;
            }
            set {
                this.anasayfadagosterField = value;
                this.RaisePropertyChanged("anasayfadagoster");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string googleanahtar {
            get {
                return this.googleanahtarField;
            }
            set {
                this.googleanahtarField = value;
                this.RaisePropertyChanged("googleanahtar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string googleaciklama {
            get {
                return this.googleaciklamaField;
            }
            set {
                this.googleaciklamaField = value;
                this.RaisePropertyChanged("googleaciklama");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProduct", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SoaForm.ServiceReference1.UserDetails UserDetails;
        
        public GetProductRequest() {
        }
        
        public GetProductRequest(SoaForm.ServiceReference1.UserDetails UserDetails) {
            this.UserDetails = UserDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SoaForm.ServiceReference1.urunler[] GetProductResult;
        
        public GetProductResponse() {
        }
        
        public GetProductResponse(SoaForm.ServiceReference1.urunler[] GetProductResult) {
            this.GetProductResult = GetProductResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServisimSoapChannel : SoaForm.ServiceReference1.ServisimSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServisimSoapClient : System.ServiceModel.ClientBase<SoaForm.ServiceReference1.ServisimSoap>, SoaForm.ServiceReference1.ServisimSoap {
        
        public ServisimSoapClient() {
        }
        
        public ServisimSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServisimSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServisimSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServisimSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoaForm.ServiceReference1.GetProductResponse SoaForm.ServiceReference1.ServisimSoap.GetProduct(SoaForm.ServiceReference1.GetProductRequest request) {
            return base.Channel.GetProduct(request);
        }
        
        public SoaForm.ServiceReference1.urunler[] GetProduct(SoaForm.ServiceReference1.UserDetails UserDetails) {
            SoaForm.ServiceReference1.GetProductRequest inValue = new SoaForm.ServiceReference1.GetProductRequest();
            inValue.UserDetails = UserDetails;
            SoaForm.ServiceReference1.GetProductResponse retVal = ((SoaForm.ServiceReference1.ServisimSoap)(this)).GetProduct(inValue);
            return retVal.GetProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoaForm.ServiceReference1.GetProductResponse> SoaForm.ServiceReference1.ServisimSoap.GetProductAsync(SoaForm.ServiceReference1.GetProductRequest request) {
            return base.Channel.GetProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoaForm.ServiceReference1.GetProductResponse> GetProductAsync(SoaForm.ServiceReference1.UserDetails UserDetails) {
            SoaForm.ServiceReference1.GetProductRequest inValue = new SoaForm.ServiceReference1.GetProductRequest();
            inValue.UserDetails = UserDetails;
            return ((SoaForm.ServiceReference1.ServisimSoap)(this)).GetProductAsync(inValue);
        }
    }
}
